import test from 'node:test';import assert from 'node:assert/strict';
import {sheetFramework,markSummary} from '../server/assessment-sheets.mjs';
import {dispatch} from '../server/domain.mjs';
const sig={signature:'Test name',declaration:true};
function fixture(){let n=0;const student={id:'s',name:'Student',role:'learner',course:'vrq',academy:'a',active:true},admin={id:'a',name:'Admin',role:'admin',active:true},tutor={id:'t',name:'Tutor',role:'tutor',academies:['a'],active:true},items=[];const store={profile:async id=>id==='s'?student:null,record:async id=>items.find(r=>r.id===id),records:async id=>items.filter(r=>r.learner===id),list:async(_,filters)=>items.filter(r=>filters.every(([k,v])=>r[k]===v)),add:async(r,id)=>{const row={...r,id:id||'r'+(++n),created:new Date(Date.UTC(2026,8,29,0,0,n)).toISOString()};items.push(row);return row;}};return {student,admin,tutor,store,items};}
test('photographed service columns are distinct and maximum marks match conversion charts',()=>{for(const [unit,rows,max] of [['203',9,15],['204',9,17],['211',13,23],['210',15,25]]){const f=sheetFramework(unit);assert.equal(f.criteria.length,rows*f.marking.ranges.length);assert.equal(f.marking.maxMarks.slice(0,rows).reduce((a,b)=>a+b,0),max);assert.equal(markSummary(f.marking,Object.fromEntries(f.marking.maxMarks.map((v,i)=>[String(i),v])))[0].grade,'Distinction');}assert.equal(sheetFramework('211').marking.ranges.includes('Partial beard'),false);});
test('unmet criterion cannot pass through a high total; blanks stay incomplete; missing page cannot grade',()=>{const f=sheetFramework('211'),marks=Object.fromEntries(f.marking.maxMarks.slice(0,13).map((v,i)=>[String(i),v]));marks['0']=0;assert.equal(markSummary(f.marking,marks)[0].grade,'Not yet achieved');delete marks['0'];assert.equal(markSummary(f.marking,marks)[0].grade,'Incomplete');const partial=sheetFramework('210');partial.marking.complete=false;assert.equal(markSummary(partial.marking,Object.fromEntries(partial.marking.maxMarks.map((v,i)=>[String(i),v])))[0].grade,'Awaiting missing sheet');});
test('202 records four tasks OR one online test, not both as mandatory practical services',()=>{assert.equal(sheetFramework('202','tasks').criteria.length,4);assert.equal(sheetFramework('202','online').criteria.length,1);assert.equal(sheetFramework('202').marking.knowledge,true);});
test('preset restricted to VRQ, remains observation-only, and cannot be final-signed as a complete unit',async()=>{const c=fixture();await assert.rejects(dispatch(c.store,c.admin,'framework',{sheetPreset:true,course:'nvq6008',unit:'215',confirmed:true}),/VRQ only/);const f=await dispatch(c.store,c.admin,'framework',{sheetPreset:true,course:'vrq',unit:'211',confirmed:true});assert.equal(f.payload.unitCompletionReady,false);await assert.rejects(dispatch(c.store,c.tutor,'unitSignoff',{...sig,learner:'s',unit:'211',framework:f.id,checks:[]}),/observation sheet only/);});
test('signed consultation choices retained; assessor marks validated against learner claims and sheet scale',async()=>{const c=fixture(),f=await dispatch(c.store,c.admin,'framework',{sheetPreset:true,course:'vrq',unit:'211',confirmed:true});const input={...sig,learner:'s',units:['211'],date:'2026-09-29',consultation:'Agreed plan',consultationPlan:{facialLooks:['Partial beard'],texture:['Coarse'],contraindications:['No']},service:'Beard service',reflection:'Reflection',criteria:[{unit:'211',frameworkId:f.id,checks:['0','1']}]};const p=await dispatch(c.store,c.student,'practical',input);assert.deepEqual(p.payload.consultationPlan.facialLooks,['Partial beard']);assert.equal(p.payload.consultationPlan.contraindications[1],'Not assessed');const assess={...sig,id:p.id,outcome:'achieved',feedback:'Observed',criteria:input.criteria};await assert.rejects(dispatch(c.store,c.tutor,'assessment',{...assess,marking:[{frameworkId:f.id,marks:{'0':3,'1':3}}]}),/Invalid mark/);await assert.rejects(dispatch(c.store,c.tutor,'assessment',{...assess,marking:[{frameworkId:f.id,marks:{'0':1,'1':0}}]}),/positive assessor mark/);const a=await dispatch(c.store,c.tutor,'assessment',{...assess,marking:[{frameworkId:f.id,marks:{'0':1,'1':3}}]});assert.equal(a.payload.marking[0].summary[0].grade,'Incomplete');assert.equal(a.payload.marking[0].summary[0].total,4);await assert.rejects(dispatch(c.store,c.student,'practical',{...input,consultationPlan:{texture:['Invented']}}),/Invalid consultation/);});

test('Unit 210 continuation grades both styles independently at every band boundary',()=>{const f=sheetFramework('210');assert.equal(f.marking.rows,15);assert.equal(f.criteria.length,30);assert.equal(f.marking.complete,true);assert.deepEqual(f.marking.maxMarks.slice(11,15),[1,1,3,3]);for(const [total,grade] of [[15,'Pass'],[17,'Pass'],[18,'Merit'],[22,'Merit'],[23,'Distinction'],[25,'Distinction']]){const marks=Object.fromEntries(Array.from({length:15},(_,i)=>[String(i),1]));let extra=total-15;for(const i of [1,2,4,13,14]){const add=Math.min(extra,2);marks[String(i)]+=add;extra-=add;}let results=markSummary(f.marking,marks);assert.equal(results[0].total,total);assert.equal(results[0].grade,grade);assert.equal(results[1].grade,'Incomplete');marks['12']=0;assert.equal(markSummary(f.marking,marks)[0].grade,'Not yet achieved');}});
