import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright-core');
import {dispatch} from '../server/domain.mjs';import {CONFIG} from '../server/config.mjs';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url)));
const people=[{id:CONFIG.owner,name:'Shane Spellacey',email:CONFIG.email,role:'admin',academies:[],learners:[],active:true,mustChange:false},{id:'learner1',name:'Fictional Learner',email:'learner@example.test',role:'learner',academy:'academy1',academies:[],learners:[],course:'vrq',start:'2026-09-01',active:true,mustChange:false,optionalUnits:[],details:{}},{id:'tutor1',name:'Fictional Tutor',email:'tutor@example.test',role:'tutor',academies:['academy1'],learners:[],active:true,mustChange:false},{id:'iqa1',name:'Fictional IQA',email:'iqa@example.test',role:'iqa',academies:[],learners:[],active:true,mustChange:false}];
const items=[],academies=[{id:'academy1',name:'Hairforce1 Training Academy'}];
const store={profiles:async()=>people,profile:async id=>people.find(p=>p.id===id),academies:async()=>academies,academy:async name=>{academies.push({id:'academy'+(academies.length+1),name});return {ok:true};},list:async(_,f)=>items.filter(r=>f.every(([k,v])=>r[k]===v)),record:async id=>items.find(r=>r.id===id),records:async id=>items.filter(r=>r.learner===id),add:async(r,id='r'+items.length)=>{if(items.some(x=>x.id===id))throw Object.assign(Error('Conflict'),{code:409});const item={...r,id,created:new Date().toISOString()};items.push(item);return item;}};
const server=http.createServer((req,res)=>{const p=decodeURIComponent(req.url.split('?')[0]);const relative=p.replace('/HF-Training-Website/','')||'index.html';const target=path.resolve(root,relative);if(!target.startsWith(root+'/')){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',target.endsWith('.html')?'text/html':target.endsWith('.svg')?'image/svg+xml':'application/json');res.end(fs.readFileSync(target));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(8124,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'],headless:true});
try{
 const context=await browser.newContext({viewport:{width:1366,height:900}});const page=await context.newPage();let actor=null;const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text());});
 await context.route('https://fra.cloud.appwrite.io/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.postData()?JSON.parse(req.postData()):{};let response={},status=200;
 if(url.pathname.endsWith('/account/sessions/email')){actor=people.find(p=>p.email.toLowerCase()===body.email.toLowerCase());status=actor?201:401;response=actor?{$id:'session'}:{message:'Invalid account',code:401};}
 else if(url.pathname.endsWith('/account/sessions/current')){actor=null;status=204;}
 else if(url.pathname.endsWith('/account')){if(!actor){status=401;response={message:'Sign in',code:401};}else response={$id:actor.id,name:actor.name,email:actor.email,emailVerification:true,status:true,labels:actor.role==='admin'?['hfadmin']:[]};}
 else if(url.pathname.includes('/executions')){let out,code=200;try{const payload=JSON.parse(body.body);out=await dispatch(store,actor,payload.action,payload.input);if(payload.action==='me')out.verified=true;}catch(e){out={error:e.message};code=e.code||400;}response={status:'completed',responseStatusCode:code,responseBody:JSON.stringify(out)};}
 else {status=400;response={message:'Unmocked route'};}
 await route.fulfill({status,contentType:status===204?'text/plain':'application/json',body:status===204?'':JSON.stringify(response),headers:{'access-control-allow-origin':'http://127.0.0.1:8124','access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-appwrite-project,x-appwrite-response-format,x-sdk-name,x-sdk-platform,x-sdk-language,x-sdk-version'}});
 });
 const go=async email=>{await page.goto('http://127.0.0.1:8124/HF-Training-Website/');await page.locator('#login-form [name=email]').fill(email);await page.locator('#login-form [name=password]').fill('Fictional-test-password-only');await page.locator('#signin').click();await page.locator('#workspace').waitFor({state:'visible',timeout:8000}).catch(async e=>{console.log('LOGIN',await page.locator('#login-error').textContent());throw e;});};
 await page.goto('http://127.0.0.1:8124/HF-Training-Website/');await page.screenshot({path:root+'/docs/LOGIN.png',fullPage:true});
 await go(CONFIG.email);await page.locator('[data-page=academies]').click();await page.locator('#academy [name=name]').fill('Second Academy');await page.locator('#academy button').click();await page.getByRole('heading',{name:'Second Academy',exact:true}).waitFor();
 await page.locator('[data-page=overview]').click();await page.getByRole('heading',{name:'Fictional Learner',exact:true}).waitFor();await page.screenshot({path:root+'/docs/WORKSPACE.png',fullPage:true});
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('learner@example.test');assert.equal(await page.locator('[data-page=people]').count(),0);
 await page.locator('[data-page=portfolio]').click();await page.getByText('Submit practical work',{exact:true}).click();const p=page.locator('#practical');await p.locator('[name=date]').fill('2026-09-28');for(const n of ['consultation','service','reflection'])await p.locator(`[name=${n}]`).fill('Fictional service record');await p.locator('[name=declaration]').check();await p.locator('button.primary').click();await page.getByRole('heading',{name:/Practical submission.*202/}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('tutor@example.test');await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Assess submission'}).click();await page.locator('#decision [name=outcome]').selectOption('achieved');await page.locator('#decision [name=feedback]').fill('Observed evidence checked');await page.locator('#decision [name=declaration]').check();await page.locator('#decision button').click();await page.getByRole('heading',{name:/Assessor decision.*202/}).waitFor();
 await page.locator('[data-page=reviews]').click();await page.getByText('Create a signed review',{exact:true}).click();for(const n of ['progress','actions','assessorFeedback'])await page.locator(`#review [name=${n}]`).fill('Fictional review');await page.locator('#review [name=declaration]').check();await page.locator('#review button').click();await page.getByRole('heading',{name:'Progress review',exact:true}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('iqa@example.test');await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Sample assessment'}).click();for(const n of ['sampleReason','feedback'])await page.locator(`#sample [name=${n}]`).fill('Fictional sample checked');for(const n of ['authentic','sufficient','fair','declaration'])await page.locator(`#sample [name=${n}]`).check();await page.locator('#sample [name=outcome]').selectOption('verified');await page.locator('#sample button').click();await page.getByRole('heading',{name:'IQA sampling',exact:true}).waitFor();
 await page.locator('#safety').click();await page.getByRole('heading',{name:'Safeguarding & support'}).waitFor();assert.equal(await page.getByRole('link',{name:'Childline support'}).getAttribute('href'),'https://www.childline.org.uk/get-support/');await page.locator('#close-modal').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'/docs/PHONE.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);assert.deepEqual(errors,[]);console.log('Browser: admin academy creation, learner submission, tutor decision, review creation, IQA sample, support links and mobile layout passed. API calls simulated with the real domain logic; live cloud not tested.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
