import {Client,Account,Functions} from 'appwrite';
import {CONFIG,COURSES} from '../server/config.mjs';
const client=new Client().setEndpoint(CONFIG.endpoint).setProject(CONFIG.project);
const account=new Account(client),functions=new Functions(client);
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state={me:null,verified:false,page:'overview',students:[],people:[],academies:[],lid:'',data:null};
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/London'}),later=d=>{const v=new Date(d+'T12:00:00Z');v.setUTCDate(v.getUTCDate()+28);return v.toISOString().slice(0,10);};
const f=(name,label,type='text',value='',required=true)=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${type==='password'?'minlength="16" autocomplete="new-password"':''}></label>`;
const ta=(name,label,value='',required=true)=>`<label>${esc(label)}<textarea name="${name}" maxlength="4000" ${required?'required':''}>${esc(value)}</textarea></label>`;
const options=(items,sel='')=>items.map(([v,n])=>`<option value="${esc(v)}" ${v===sel?'selected':''}>${esc(n)}</option>`).join('');
const select=(name,label,items,sel='',multiple=false)=>`<label>${esc(label)}<select name="${name}" ${multiple?'multiple':''}>${options(items,sel)}</select></label>`;
const ck=(name,label)=>`<label><input type="checkbox" name="${name}">${esc(label)}</label>`;
const sig=()=>`<fieldset><legend>Digital acknowledgement</legend>${f('signature','Type your full name','text',state.me?.name||'')}${ck('declaration','I confirm this record is accurate and intend my name to be my signature.')}</fieldset>`;
const title=(h,p='')=>`<div class="page-title"><div><h1>${esc(h)}</h1><p>${esc(p)}</p></div></div>`;
const empty=t=>`<p class="empty">${esc(t)}</p>`;
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;setTimeout(()=>$('#toast').hidden=true,6500);}
function modal(name,html){$('#modal-title').textContent=name;$('#modal-body').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();}
function bind(id,fn){const form=document.getElementById(id);if(!form)return;form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('button[type=submit],button.primary');if(b)b.disabled=true;try{await fn(form);}catch(e){notify(e.message);}finally{if(b)b.disabled=false;}});}
function data(form){const d=Object.fromEntries(new FormData(form));for(const box of form.querySelectorAll('input[type=checkbox]'))d[box.name]=box.checked;for(const sel of form.querySelectorAll('select[multiple]'))d[sel.name]=Array.from(sel.selectedOptions).map(o=>o.value);return d;}
async function api(action,input={}){
 if(!navigator.onLine)throw Error('You are offline. Reconnect before saving.');
 const result=await functions.createExecution({functionId:CONFIG.function,body:JSON.stringify({action,input}),async:false,path:'/',method:'POST'});
 let json;try{json=JSON.parse(result.responseBody);}catch{throw Error('The HF Training service is not ready. Complete the backend installation, then try again.');}
 if(result.responseStatusCode>=400||json.error)throw Error(json.error||'Request failed.');return json;
}
function fileDownload(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function roleName(r){return ({admin:'Administrator',tutor:'Assessor / tutor',iqa:'IQA',learner:'Student',employer:'Employer'})[r]||r;}
function support(){modal('Safeguarding & support',`<p>Speak to <strong>Shane Spellacey</strong> or <strong>Anderson Boyce</strong>.</p><p>If someone is in immediate danger, call <a href="tel:999">999</a>.</p><form id="support-form">${ta('message','What would you like us to know?', '',false)}<button class="primary">Open my email app</button></form><p class="small">Addressed to ${esc(CONFIG.email)}. You must press Send in your email app. This page does not send or save the message, and this inbox is not an emergency service.</p><div class="help-links"><a href="https://www.childline.org.uk/get-support/" target="_blank" rel="noopener noreferrer">Childline support</a><a href="https://www.samaritans.org/how-we-can-help/contact-samaritan/" target="_blank" rel="noopener noreferrer">Samaritans support</a></div><p><button id="copy-email" class="quiet">Copy support email</button></p>`);bind('support-form',async form=>{const message=form.elements.message.value;location.href=`mailto:${CONFIG.email}?subject=${encodeURIComponent('HF Training — support request')}&body=${encodeURIComponent(message)}`;});$('#copy-email').onclick=()=>navigator.clipboard.writeText(CONFIG.email).then(()=>notify('Email address copied.')).catch(()=>notify(CONFIG.email));}
$('#safety').onclick=support;$('#close-modal').onclick=()=>{$('#modal').close();$('#modal-body').innerHTML='';};
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();$('#signin').disabled=true;$('#login-error').textContent='';try{let existing=null;try{existing=await account.get();}catch(err){if(err.code!==401)throw err;}if(existing)await account.deleteSession({sessionId:'current'});await account.createEmailPasswordSession({email:e.target.email.value.trim(),password:e.target.password.value});e.target.password.value='';await boot();}catch(e){$('#login-error').textContent=e.message||'Sign-in failed.';}finally{$('#signin').disabled=false;}});
$('#logout').onclick=async()=>{try{await account.deleteSession({sessionId:'current'});location.href=location.pathname;}catch(e){notify('Sign-out could not be confirmed. Reconnect and try again.');}};
$('#forgot').onclick=()=>{modal('Reset your password',`<form id="recover">${f('email','Account email','email')}<button class="primary">Request reset link</button></form>`);bind('recover',async form=>{try{await account.createRecovery({email:form.email.value,url:CONFIG.url+'?flow=recovery'});}catch{}modal('Check your inbox','<p>If the account exists and the request is accepted, an email will explain how to reset your password.</p>');});};
async function boot(){
 const me=await api('me');state.me=me.user;state.verified=me.verified;
 $('#login').hidden=true;$('#workspace').hidden=false;$('#identity').textContent=state.me.name+' · '+roleName(state.me.role);
 if(state.me.mustChange||!state.verified)state.page='account';await refresh();
}
function nav(){const items=[['overview','Overview'],['portfolio','E-portfolio'],['attendance','Attendance'],['hours','Learning hours'],['reviews','Progress reviews'],['exams','Exam results'],['resources','Learning resources'],['consent','Photo consent'],['academies','Academies'],['people','People & enrolment'],['framework','Unit checklists'],['account','My account']].filter(([key])=>!(['academies','people','framework'].includes(key)&&state.me.role!=='admin')&&!(state.me.role==='employer'&&['portfolio','attendance','hours','consent','exams','resources'].includes(key))&&!(state.me.role!=='learner'&&key==='consent')&&(!state.me.mustChange&&state.verified||key==='account'));$('#nav').innerHTML=items.map(([key,label],i)=>`<button data-page="${key}" class="${key===state.page?'active':''}"><span>${String(i+1).padStart(2,'0')}</span>${label}</button>`).join('');$('#nav').querySelectorAll('button').forEach(b=>b.onclick=async()=>{state.page=b.dataset.page;try{await refresh();}catch(e){notify(e.message);}});$('#breadcrumb').textContent=items.find(i=>i[0]===state.page)?.[1]||'Workspace';}
async function refresh(){nav();$('#picker').innerHTML='';$('#content').innerHTML='<p class="notice">Loading workspace…</p>';$('#notice').innerHTML='';
 if(state.page==='account'){renderAccount();return;}
 const work=await api('workspace');Object.assign(state,work);
 if(!state.students.some(p=>p.id===state.lid))state.lid=state.students[0]?.id||'';
 if(['academies','people','framework'].includes(state.page)){renderAdmin();return;}
 if(state.students.length&&state.me.role!=='learner'){$('#picker').innerHTML=select('student','Student workspace',state.students.map(p=>[p.id,p.name]),state.lid);$('#picker select').onchange=async e=>{state.lid=e.target.value;try{await refresh();}catch(err){notify(err.message);}};}
 state.data=state.lid?await api('learner',{id:state.lid}):null;
 if(!state.data){$('#content').innerHTML=title('Your workspace')+empty(state.me.role==='admin'?'Start by adding people and assigning them to an academy.':'No students have been assigned to this account. Contact your administrator.');return;}
 renderLearner();
}
function renderAccount(){
 $('#content').innerHTML=title('My account','Manage your sign-in details.')+(!state.verified?'<section class="notice">Verify your email address before opening student records. <button id="verify">Send verification email</button> <button id="check-verify">Check verification</button></section>':'')+(state.me.mustChange?'<section class="notice">Please replace your temporary password before continuing.</section>':'')+`<section class="card"><form id="password">${f('current','Current password','password')}${f('password','New password · at least 16 characters','password')}<button class="primary">Change password</button></form></section>`;
 $('#content input[name=current]').autocomplete='current-password';
 if($('#verify'))$('#verify').onclick=async()=>{try{await account.createVerification({url:CONFIG.url+'?flow=verify'});notify('Verification email requested. Check your inbox.');}catch(e){notify(e.message);}};
 if($('#check-verify'))$('#check-verify').onclick=async()=>{try{await boot();notify(state.verified?'Email verified.':'Email not yet verified.');}catch(e){notify(e.message);}};
 bind('password',async form=>{await api('changePassword',data(form));form.reset();await boot();notify('Password changed.');});
}
function renderAdmin(){
 const root=$('#content');
 if(state.page==='academies'){root.innerHTML=title('Academies','Create an academy before enrolling its students.')+`<section class="card"><form id="academy">${f('name','Academy name')}<button class="primary">Add academy</button></form></section>`+state.academies.map(a=>`<section class="card"><h3>${esc(a.name)}</h3><p>${state.students.filter(p=>p.academy===a.id).length} students</p></section>`).join('');bind('academy',async form=>{await api('academyCreate',data(form));await refresh();notify('Academy added.');});return;}
 if(state.page==='framework'){root.innerHTML=title('Unit checklists','Publish centre-approved criteria before signing off complete units.')+`<section class="notice">Unit headings are provided. Full performance criteria, range and knowledge requirements must be checked against your approved handbook. A practical pass alone does not complete a qualification.</section><section class="card"><form id="framework">${select('course','Course',Object.entries(COURSES).map(([k,v])=>[k,v.name]))}<div id="unit-choice"></div>${f('source','Handbook reference and version')}${ta('criteria','One assessment requirement per line')}${ck('confirmed','I have checked this list against the correct approved handbook, including range, knowledge and observation requirements.')}<button class="primary">Publish checklist version</button></form></section>`;const update=()=>{const c=COURSES[$('#framework select[name=course]').value];$('#unit-choice').innerHTML=select('unit','Unit',[...c.units,...(c.optional||[])]);};update();$('#framework select[name=course]').onchange=update;bind('framework',async form=>{await api('framework',data(form));form.reset();notify('Checklist published. Previous sign-offs retain their original version.');});return;}
 root.innerHTML=title('People & enrolment','Create accounts, assign academies and enrol students.')+`<details><summary>Add a person</summary><form id="person"><div class="form-grid">${f('first','First name')}${f('last','Last name')}${f('email','Email address','email')}${select('role','Role',[['learner','Student'],['tutor','Assessor / tutor'],['iqa','IQA'],['employer','Employer'],['admin','Administrator']])}${select('academy','Academy · students and tutors',state.academies.map(a=>[a.id,a.name]))}${select('course','Student course',Object.entries(COURSES).map(([k,v])=>[k,v.name]))}</div><fieldset id="enrolment"><legend>Student enrolment details</legend><div class="form-grid">${f('dob','Date of birth','date','',false)}${f('start','Course start date','date',today(),false)}${f('phone','Phone','tel','',false)}${f('address','Address','text','',false)}${f('postcode','Postcode','text','',false)}${f('emergencyName','Emergency contact name','text','',false)}${f('emergencyPhone','Emergency contact phone','tel','',false)}${f('guardianName','Parent/carer name, where appropriate','text','',false)}${f('guardianEmail','Parent/carer email, where appropriate','email','',false)}${f('employerName','Employer / placement name','text','',false)}</div>${select('optionalUnits','6008 optional units · hold Ctrl to choose several',COURSES.nvq6008.optional,'',true)}<p class="small">Optional-unit choices must satisfy your approved qualification requirements. The app does not certify an apprenticeship or calculate funding eligibility. Photo consent is completed by the student after sign-in.</p></fieldset>${select('learners','Employer: assigned students',state.students.map(p=>[p.id,p.name]),'',true)}<button class="primary">Create account</button></form></details><section class="card"><h3>People</h3>${state.people.map(p=>`<div class="unit-row"><div class="unit-copy"><strong>${esc(p.name)}</strong><p>${esc(roleName(p.role))} · ${p.active?'Active':'Disabled'}</p></div>${['learner','tutor','employer'].includes(p.role)?`<button data-assign="${p.id}">Assign</button>`:''}${p.id!==CONFIG.owner&&p.id!==state.me.id&&p.active?`<button data-disable="${p.id}" class="quiet">Disable</button>`:''}</div>`).join('')}</section>`;
 bind('person',async form=>{const d=data(form);if(d.course!=='nvq6008')d.optionalUnits=[];const r=await api('personCreate',d);await refresh();modal('Account created',`<p>Share these details privately with this person. The temporary password is shown only in this response.</p><p>Email: <strong>${esc(r.email)}</strong></p><p>Temporary password: <code>${esc(r.password)}</code></p><p>They must change it and verify their email before accessing records.</p>`);});
 root.querySelectorAll('[data-disable]').forEach(b=>b.onclick=async()=>{if(confirm('Disable this account?'))try{await api('personDisable',{id:b.dataset.disable});await refresh();}catch(e){notify(e.message);}});
 root.querySelectorAll('[data-assign]').forEach(b=>b.onclick=()=>{const p=state.people.find(p=>p.id===b.dataset.assign);modal('Assign '+p.name,`<form id="assign">${p.role==='learner'?select('academy','Academy',state.academies.map(a=>[a.id,a.name]),p.academy):select('ids',p.role==='tutor'?'Academies':'Students',(p.role==='tutor'?state.academies:state.students).map(a=>[a.id,a.name]),'',true)}<p class="small">The selection replaces the current assignment.</p><button class="primary">Save assignment</button></form>`);if(p.role!=='learner')for(const o of $('#assign select').options)o.selected=(p.role==='tutor'?p.academies:p.learners).includes(o.value);bind('assign',async form=>{await api('assign',{...data(form),id:p.id});$('#modal').close();await refresh();});});
}
function formBox(id,h,fields,button){return `<details><summary>${h}</summary><form id="${id}">${fields}<button class="primary">${button}</button></form></details>`;}
function saveForm(id,action,extra={}){bind(id,async form=>{await api(action,{...data(form),learner:state.lid,...extra});await refresh();notify('Record saved.');});}
const fieldLabels={date:'Date',unit:'Unit',consultation:'Consultation and safety',service:'Service carried out',reflection:'Learner reflection',ranges:'Techniques and ranges',outcome:'Outcome',feedback:'Feedback',sampleReason:'Reason for sampling',nextDate:'Next review',progress:'Progress',actions:'Agreed actions',assessorFeedback:'Assessor feedback',employerRequired:'Employer signature required',teaching:'Teaching image permission',marketing:'Marketing image permission',wording:'Consent declaration',version:'Form version',minutes:'Minutes',status:'Attendance',note:'Notes',activity:'Learning activity',category:'Learning location',reference:'Reference',notes:'Notes',title:'Title',body:'Learning material',url:'Link',source:'Handbook reference',evidence:'Evidence and justification'};
const recordNames={practical:'Practical submission',assessment:'Assessor decision',iqa:'IQA sampling',review:'Progress review',signature:'Review signature',approval:'Administrator decision',unitSignoff:'Unit sign-off',consent:'Photo consent',attendance:'Attendance record',hours:'Learning hours',exam:'Exam result',resource:'Learning resource'};
function recordCard(r,buttons=''){return `<article class="record"><h3>${esc(recordNames[r.kind]||r.kind)} ${r.payload.unit?esc('· Unit '+r.payload.unit):''}</h3><p class="small">${esc(r.payload.date||r.created?.slice(0,10))} · ${esc(r.payload.actorName||'')}</p><dl>${Object.entries(r.payload).filter(([k,v])=>!['actorName','digest','reviewDigest','signature','framework','frameworkId','attendance','unit'].includes(k)&&typeof v!=='object').map(([k,v])=>`<dt>${esc(fieldLabels[k]||k)}</dt><dd>${esc(typeof v==='boolean'?(v?'Yes':'No'):v)}</dd>`).join('')}</dl>${r.payload.signature?`<p class="small">Signed by ${esc(r.payload.signature.name)} · ${esc(new Date(r.payload.signature.signedAt).toLocaleString('en-GB',{timeZone:'Europe/London'}))}</p>`:''}${buttons}</article>`;}
function renderLearner(){const {student:p,records,units,frameworks}=state.data,root=$('#content'),staff=['admin','tutor'].includes(state.me.role),own=state.me.id===p.id;const by=k=>records.filter(r=>r.kind===k).sort((a,b)=>b.created.localeCompare(a.created));
 if(state.page==='overview'){const rs=by('review'),due=later(rs[0]?.payload.date||p.start);root.innerHTML=title(p.name,COURSES[p.course]?.name)+`<section class="hero"><div><p class="eyebrow">YOUR NEXT STEP</p><h2>Build your skills. See your progress.</h2><p>Your academy, evidence and feedback in one workspace.</p></div><div><span class="big-percent">${units.length}</span><span class="small">enrolled units</span></div></section><div class="stats"><div class="stat"><p>Practical submissions</p><strong>${by('practical').length}</strong></div><div class="stat"><p>Unit sign-off records</p><strong>${new Set(by('unitSignoff').map(r=>r.payload.unit)).size}</strong></div><div class="stat"><p>Learning hours logged</p><strong>${(by('hours').reduce((s,r)=>s+r.payload.minutes,0)/60).toFixed(1)}</strong></div><div class="stat"><p>${p.course==='vrq'?'Four-week review due':'Next review target'}</p><strong style="font-size:20px">${esc(due)}</strong></div></div><section class="card"><h3>Your units</h3>${units.map(([id,name])=>`<div class="unit-row"><span class="unit-icon">${id}</span><div class="unit-copy"><strong>${esc(name)}</strong><p>${by('unitSignoff').some(r=>r.payload.unit===id)?'Sign-off recorded — check IQA feedback':'In progress'}</p></div></div>`).join('')}</section>${state.me.role==='admin'?'<button id="export">Export student record</button>':''}`;if($('#export'))$('#export').onclick=async()=>{try{const x=await api('export',{learner:p.id});fileDownload('HF-student-record.json',new Blob([JSON.stringify(x,null,2)],{type:'application/json'}));}catch(e){notify(e.message);}};return;}
 if(state.page==='resources'){
 root.innerHTML=title('Learning resources',COURSES[p.course].name)+(state.me.role==='admin'?formBox('resource','Publish a resource',f('title','Title')+ta('body','Learning material')+f('url','Optional https:// link','url','',false),'Publish to this course'):'')+state.data.resources.map(r=>recordCard(r,r.payload.url?`<a href="${esc(r.payload.url)}" target="_blank" rel="noopener noreferrer">Open resource</a>`:'')).join('');saveForm('resource','resource',{course:p.course});return;
 }
 if(state.page==='exams'){
 root.innerHTML=title('Exam results',p.name)+(staff?formBox('exam','Record an exam result',select('unit','Unit',units)+f('date','Exam date','date',today())+select('outcome','Result',[['pending','Pending'],['pass','Pass'],['refer','Refer']])+f('reference','Exam / result reference')+ta('notes','Notes','',false),'Save result'):'')+by('exam').map(r=>recordCard(r)).join('');saveForm('exam','exam');return;
 }
 if(state.page==='attendance'){root.innerHTML=title('Attendance',p.name)+(staff?formBox('attendance','Record attendance',f('date','Session date','date',today())+select('status','Attendance',[['present','Present'],['late','Late'],['absent','Absent'],['authorised','Authorised absence']])+f('minutes','Minutes attended','number','360')+ta('note','Notes','',false),'Save attendance'):'')+by('attendance').map(r=>recordCard(r)).join('');saveForm('attendance','attendance');return;}
 if(state.page==='hours'){root.innerHTML=title('Learning hours',p.name)+(own||staff?formBox('hours','Add learning hours',f('date','Date','date',today())+f('minutes','Minutes','number','60')+select('category','Location',[['academy','Academy'],['workplace','Workplace'],['independent','Independent learning']])+ta('activity','Activity')+ta('reflection','What did you learn?'),'Save learning record'):'')+by('hours').map(r=>recordCard(r)).join('');saveForm('hours','hours');return;}
 if(state.page==='consent'){root.innerHTML=title('Photo consent','Your choices are recorded separately and can be changed.')+formBox('consent','Record my choices',select('teaching','Use my image for internal teaching',[['no','No'],['yes','Yes']])+select('marketing','Use my image for public marketing',[['no','No'],['yes','Yes']])+`<p>You can withdraw permission by recording new choices or contacting your academy. Refusing marketing does not affect your training.</p>`+sig(),'Save my consent choices')+by('consent').map(r=>recordCard(r)).join('');saveForm('consent','consent');return;}
 if(state.page==='reviews'){renderReviews(p,by,staff,own);return;}
 root.innerHTML=title('E-portfolio',p.name)+((own||staff)?formBox('upload','Add evidence document',`<label>PDF, JPG or PNG · maximum 1 MB<input name="file" type="file" accept=".pdf,.jpg,.jpeg,.png" required></label>`,'Upload privately'):'')+`<section class="card"><h3>Evidence documents</h3>${by('file').map(r=>`<p><button data-file="${r.id}">${esc(r.payload.name)}</button> <span class="small">${Math.ceil(r.payload.size/1024)} KB</span></p>`).join('')||empty('No evidence uploaded yet.')}</section>`+(own?formBox('practical','Submit practical work',select('unit','Unit',units)+f('date','Service date','date',today())+ta('consultation','Consultation and health & safety')+ta('service','Service carried out')+ta('reflection','Reflection and next steps')+ta('ranges','Techniques / ranges demonstrated','',false)+select('files','Evidence files · hold Ctrl to select several',by('file').map(r=>[r.id,r.payload.name]),'',true)+sig(),'Submit signed record'):'')+(staff?formBox('signoff','Sign off a complete unit',select('unit','Unit',units)+'<div id="checklist"></div>'+ta('evidence','Evidence references and justification')+sig(),'Sign off unit'):'')+by('practical').map(r=>{const a=records.find(x=>x.kind==='assessment'&&x.ref===r.id);return recordCard(r,staff&&!a?`<button data-assess="${r.id}">Assess submission</button>`:'')+(a?recordCard(a,['admin','iqa'].includes(state.me.role)&&a.actor!==state.me.id&&!records.some(x=>x.kind==='iqa'&&x.ref===a.id)?`<button data-iqa="${a.id}">Sample assessment</button>`:''):'');}).join('')+by('unitSignoff').map(r=>recordCard(r,['admin','iqa'].includes(state.me.role)&&r.actor!==state.me.id&&!records.some(x=>x.kind==='iqa'&&x.ref===r.id)?`<button data-iqa="${r.id}">Sample unit sign-off</button>`:'')).join('')+by('iqa').map(r=>recordCard(r)).join('');
 bind('upload',async form=>{const file=form.file.files[0];if(file.size>1048576)throw Error('Please choose a file no larger than 1 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});await api('fileUpload',{learner:p.id,name:file.name,base64});await refresh();notify('Evidence uploaded.');});
 root.querySelectorAll('[data-file]').forEach(b=>b.onclick=async()=>{try{const r=await api('fileDownload',{id:b.dataset.file});fileDownload(r.name,new Blob([Uint8Array.from(atob(r.base64),c=>c.charCodeAt(0))],{type:'application/octet-stream'}));}catch(e){notify(e.message);}});
 saveForm('practical','practical');
 root.querySelectorAll('[data-assess]').forEach(b=>b.onclick=()=>{modal('Assessor decision',`<form id="decision">${select('outcome','Outcome',[['returned','Further work required'],['achieved','Practical achieved']])}${ta('feedback','Feedback')}${sig()}<button class="primary">Save signed decision</button></form>`);bind('decision',async form=>{await api('assessment',{...data(form),id:b.dataset.assess});$('#modal').close();await refresh();});});
 root.querySelectorAll('[data-iqa]').forEach(b=>b.onclick=()=>{modal('IQA sampling',`<form id="sample">${ta('sampleReason','Reason for selecting this sample')}${ck('authentic','Evidence is authentic')}${ck('sufficient','Evidence is sufficient for the recorded decision')}${ck('fair','Assessment is fair and consistent')}${select('outcome','Sampling result',[['action_required','Action required'],['verified','Verified']])}${ta('feedback','Feedback and required actions')}${sig()}<button class="primary">Record sampling decision</button></form>`);bind('sample',async form=>{await api('iqa',{...data(form),id:b.dataset.iqa});$('#modal').close();await refresh();});});
 if($('#signoff')){const update=()=>{const unit=$('#signoff select[name=unit]').value,f=frameworks.filter(r=>r.payload.unit===unit).sort((a,b)=>b.created.localeCompare(a.created))[0];$('#checklist').innerHTML=f?`<input type="hidden" name="framework" value="${f.id}"><p class="small">Source: ${esc(f.payload.source)}</p><div class="checks">${f.payload.criteria.map((s,i)=>ck('check_'+i,s)).join('')}</div>`:'<p class="notice">An administrator must publish the approved checklist for this unit first.</p>';};update();$('#signoff select').onchange=update;bind('signoff',async form=>{const d=data(form);d.checks=Object.keys(d).filter(k=>k.startsWith('check_')&&d[k]).map(k=>k.slice(6));await api('unitSignoff',{...d,learner:p.id});await refresh();notify('Unit sign-off recorded.');});}
}
function renderReviews(p,by,staff,own){const records=state.data.records;$('#content').innerHTML=title('Progress reviews',p.course==='vrq'?'VRQ reviews every four weeks.':'Review progress and agreed next steps.')+(staff?formBox('review','Create a signed review',f('date','Review date','date',today())+f('nextDate','Next review date','date',later(today()))+ta('progress','Progress against units and wellbeing discussed')+ta('assessorFeedback','Assessor feedback')+ta('actions','Agreed actions and targets')+ck('employerRequired','Employer feedback and signature required')+'<p class="small">The current attendance record is attached as a snapshot. Student and employer feedback are added under their own logins.</p>'+sig(),'Create review for signatures'):'')+by('review').map(r=>{const sigs=records.filter(s=>s.kind==='signature'&&s.ref===r.id),approval=records.find(s=>s.kind==='approval'&&s.ref===r.id);return recordCard(r,`<details><summary>Attendance snapshot (${r.payload.attendance.length} records)</summary>${r.payload.attendance.map(a=>`<p>${esc(a.date)} · ${esc(a.status)} · ${a.minutes} minutes</p>`).join('')||'<p>No attendance records.</p>'}</details>${(own||state.me.role==='employer')&&!sigs.some(s=>s.payload.signature.role===state.me.role)?`<button data-sign="${r.id}">Add feedback & sign</button>`:''}${state.me.role==='admin'&&!approval?`<button data-approve="${r.id}">Approve / return</button>`:''}<p><a href="mailto:${CONFIG.email}?subject=${encodeURIComponent('HF Training review ready')}&body=${encodeURIComponent('Please sign in to review record '+r.id+' at '+CONFIG.url)}">Open email to administrator</a></p>`)+sigs.map(s=>recordCard(s)).join('')+(approval?recordCard(approval):'<p class="small">Awaiting administrator decision.</p>');}).join('');saveForm('review','review');$('#content').querySelectorAll('[data-sign],[data-approve]').forEach(b=>b.onclick=()=>{const approving=!!b.dataset.approve;modal(approving?'Administrator approval':'Review feedback and signature',`<form id="review-action">${approving?select('outcome','Decision',[['returned','Return for a new review'],['approved','Approve']]):''}${ta('feedback','Feedback')}${sig()}<button class="primary">Save signed response</button></form>`);bind('review-action',async form=>{await api(approving?'reviewApprove':'reviewSign',{...data(form),id:b.dataset.approve||b.dataset.sign});$('#modal').close();await refresh();});});}
async function start(){
 const u=new URL(location.href),flow=u.searchParams.get('flow'),userId=u.searchParams.get('userId'),secret=u.searchParams.get('secret');
 history.replaceState(null,'',location.pathname);$('#signin').disabled=false;$('#startup').textContent='';
 if(flow==='verify'&&userId&&secret){try{await account.updateVerification({userId,secret});notify('Email verified. You can now sign in.');}catch(e){notify('Verification link could not be used. Request a new link.');}}
 if(flow==='recovery'&&userId&&secret){modal('Choose a new password',`<form id="reset">${f('password','New password · at least 16 characters','password')}<button class="primary">Set password</button></form>`);bind('reset',async form=>{await account.updateRecovery({userId,secret,password:form.password.value});$('#modal').close();notify('Password reset. Sign in with your new password.');});return;}
 try{await account.get();await boot();}catch(e){if(e.code!==401)$('#login-error').textContent=e.message||'The service is not ready yet.';}
}
start();
