import fs from 'node:fs';import http from 'node:http';import assert from 'node:assert/strict';import path from 'node:path';
import {fileURLToPath} from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright-core');
import {dispatch} from '../server/domain.mjs';import {CONFIG} from '../server/config.mjs';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url)));
const people=[{id:CONFIG.owner,name:'Shane Spellacey',email:CONFIG.email,role:'admin',academies:[],learners:[],active:true,mustChange:false},{id:'learner1',name:'Fictional Learner',email:'learner@example.test',role:'learner',academy:'academy1',academies:[],learners:[],course:'vrq',start:'2026-09-01',active:true,mustChange:false,optionalUnits:[],details:{}},{id:'tutor1',name:'Fictional Tutor',email:'tutor@example.test',role:'tutor',academies:['academy1'],learners:[],active:true,mustChange:false},{id:'iqa1',name:'Fictional IQA',email:'iqa@example.test',role:'iqa',academies:[],learners:[],active:true,mustChange:false}];
const fileBytes=new Map();const items=[],academies=[{id:'academy1',name:'Hairforce1 Training Academy'}];
const store={putFile:async(id,bytes)=>fileBytes.set(id,bytes),file:async id=>fileBytes.get(id),setProfile:async p=>Object.assign(people.find(x=>x.id===p.id),p),profiles:async()=>people,profile:async id=>people.find(p=>p.id===id),academies:async()=>academies,academy:async name=>{academies.push({id:'academy'+(academies.length+1),name});return {ok:true};},list:async(_,f)=>items.filter(r=>f.every(([k,v])=>r[k]===v)),record:async id=>items.find(r=>r.id===id),records:async id=>items.filter(r=>r.learner===id),add:async(r,id='r'+items.length)=>{if(items.some(x=>x.id===id))throw Object.assign(Error('Conflict'),{code:409});const item={...r,id,created:new Date().toISOString()};items.push(item);return item;}};
for(const unit of ['202','203'])await dispatch(store,people[0],'framework',{course:'vrq',unit,criteria:'Test criterion A\nTest criterion B',source:'Fictional checklist for testing only',confirmed:true});
const server=http.createServer((req,res)=>{const p=decodeURIComponent(req.url.split('?')[0]);const relative=p.replace('/HF-Training-Website/','')||'index.html';const target=path.resolve(root,relative);if(!target.startsWith(root+'/')){res.writeHead(403).end();return;}try{res.setHeader('Content-Type',target.endsWith('.html')?'text/html':target.endsWith('.svg')?'image/svg+xml':'application/json');res.end(fs.readFileSync(target));}catch{res.writeHead(404).end();}});await new Promise(r=>server.listen(8124,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:process.env.CHROMIUM_ARGS?JSON.parse(process.env.CHROMIUM_ARGS):['--no-sandbox'],headless:true});
try{
 const context=await browser.newContext({viewport:{width:1366,height:900}});const page=await context.newPage();let actor=null;const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message);});page.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text());});
 await context.route('https://fra.cloud.appwrite.io/**',async route=>{const req=route.request(),url=new URL(req.url()),body=req.postData()?JSON.parse(req.postData()):{};let response={},status=200;
 if(url.pathname.endsWith('/account/sessions/email')){actor=people.find(p=>p.email.toLowerCase()===body.email.toLowerCase());status=actor?201:401;response=actor?{$id:'session'}:{message:'Invalid account',code:401};}
 else if(url.pathname.endsWith('/account/sessions/current')){actor=null;status=204;}
 else if(url.pathname.endsWith('/account')){if(!actor){status=401;response={message:'Sign in',code:401};}else response={$id:actor.id,name:actor.name,email:actor.email,emailVerification:true,status:true,labels:actor.role==='admin'?['hfadmin']:[]};}
 else if(url.pathname.includes('/executions')){let out,code=200;try{const payload=JSON.parse(body.body);out=await dispatch(store,actor,payload.action,payload.input);if(payload.action==='me')out.verified=true;}catch(e){out={error:e.message};code=e.code||400;}response={status:'completed',responseStatusCode:code,responseBody:JSON.stringify(out)};}
 else {status=400;response={message:'Unmocked route'};}
 await route.fulfill({status,contentType:status===204?'text/plain':'application/json',body:status===204?'':JSON.stringify(response),headers:{'access-control-allow-origin':'http://127.0.0.1:8124','access-control-allow-credentials':'true','access-control-allow-methods':'GET,POST,DELETE,OPTIONS','access-control-allow-headers':'content-type,x-appwrite-project,x-appwrite-response-format,x-sdk-name,x-sdk-platform,x-sdk-language,x-sdk-version'}});
 });
 const go=async email=>{await page.goto('http://127.0.0.1:8124/HF-Training-Website/');await page.locator('#login-form [name=email]').fill(email);await page.locator('#login-form [name=password]').fill('Fictional-test-password-only');await page.locator('#signin').click();await page.locator('#workspace').waitFor({state:'visible',timeout:8000}).catch(async e=>{console.log('LOGIN',await page.locator('#login-error').textContent());throw e;});};
 await page.goto('http://127.0.0.1:8124/HF-Training-Website/');await page.screenshot({path:root+'/docs/LOGIN.png',fullPage:true});
 await go(CONFIG.email);await page.locator('[data-page=people]').click();await page.getByText('Add a person',{exact:true}).click();assert.equal(await page.locator('#person [name=signup]').count(),1);await page.locator('#person [name=role]').selectOption('tutor');assert.equal(await page.locator('#enrolment').isHidden(),true);await page.locator('[data-enrolment=learner1]').click();await page.locator('#enrolment-edit [name=signup]').fill('2026-08-25');await page.locator('#enrolment-edit button').click();await page.locator('#modal').waitFor({state:'hidden'});await page.locator('[data-page=academies]').click();await page.locator('#academy [name=name]').fill('Second Academy');await page.locator('#academy button').click();await page.getByRole('heading',{name:'Second Academy',exact:true}).waitFor();
 await page.locator('[data-page=overview]').click();await page.getByRole('heading',{name:'Fictional Learner',exact:true}).waitFor();await page.screenshot({path:root+'/docs/WORKSPACE.png',fullPage:true});
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('learner@example.test');assert.equal(await page.locator('[data-page=people]').count(),0);
 await page.locator('[data-page=account]').click();await page.locator('#password [name=current]').fill('short-old');await page.locator('#password [name=password]').fill('Abcdefg1');assert.equal(await page.locator('.password-rules .met').count(),3);assert.equal(await page.locator('#password').evaluate(f=>f.checkValidity()),true);await page.locator('#student-checkin').click();await page.getByRole('button',{name:'Checked in today'}).waitFor();
 await page.locator('[data-page=placement]').click();await page.getByText('Record a placement day',{exact:true}).click();await page.locator('#placement [name=employer]').fill('Test salon');await page.locator('#placement [name=activity]').fill('Shadowed consultation');await page.locator('#placement [name=reflection]').fill('Observed how the plan was agreed');await page.locator('#placement [name=declaration]').check();await page.locator('#placement button').click();await page.getByRole('heading',{name:'Work experience log',exact:true}).waitFor();
 await page.locator('[data-page=portfolio]').click();await page.getByText('Submit assessment evidence',{exact:true}).click();const p=page.locator('#practical');await p.locator('[name=unit_202]').check();await p.locator('[name=unit_203]').check();for(const u of ['202','203']){await p.locator(`[data-criteria-unit="${u}"] summary`).click();await p.locator(`[name=criterion_${u}_0]`).check();await p.locator(`[name=criterion_${u}_1]`).check();}await p.locator('[name=date]').fill('2026-09-28');for(const n of ['consultation','service','reflection'])await p.locator(`[name=${n}]`).fill('Fictional service record');await p.locator('[name=declaration]').check();await p.locator('button.primary').click();await page.getByRole('heading',{name:/Practical submission.*202/}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('tutor@example.test');await page.locator('[data-page=register]').click();await page.locator('#load-register').click();await page.getByText('Student checked in',{exact:true}).waitFor();await page.locator('[name=include_learner1]').check();await page.locator('#register button.primary').click();await page.getByText('present · 360 min',{exact:true}).waitFor();await page.locator('[data-page=attendance]').click();await page.locator('.calendar-day.present').waitFor();assert.equal(await page.locator('.calendar-day.present').count(),1);
 await page.locator('[data-page=placement]').click();await page.getByRole('button',{name:'Review placement log'}).click();await page.locator('#placement-decision [name=outcome]').selectOption('approved');await page.locator('#placement-decision [name=feedback]').fill('Confirmed with supervisor');await page.locator('#placement-decision [name=declaration]').check();await page.locator('#placement-decision button').click();await page.getByRole('heading',{name:'Tutor placement confirmation',exact:true}).waitFor();
 await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Assess submission'}).click();for(const u of ['202','203']){await page.locator(`#decision [data-criteria-unit="${u}"] summary`).click();for(const i of ['0','1'])await page.locator(`#decision [name=criterion_${u}_${i}]`).check();}await page.locator('#decision [name=outcome]').selectOption('achieved');await page.locator('#decision [name=feedback]').fill('Observed evidence checked');await page.locator('#decision [name=declaration]').check();await page.locator('#decision button').click();await page.getByRole('heading',{name:/Assessor decision.*202/}).waitFor();
 await page.locator('[data-page=reviews]').click();await page.getByText('Create a signed review',{exact:true}).click();for(const n of ['progress','actions','assessorFeedback'])await page.locator(`#review [name=${n}]`).fill('Fictional review');await page.locator('#review [name=declaration]').check();await page.locator('#review button').click();await page.getByRole('heading',{name:'Progress review',exact:true}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('iqa@example.test');await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Sample assessment'}).click();for(const n of ['sampleReason','feedback'])await page.locator(`#sample [name=${n}]`).fill('Fictional sample checked');for(const n of ['authentic','sufficient','fair','declaration'])await page.locator(`#sample [name=${n}]`).check();await page.locator('#sample [name=outcome]').selectOption('verified');await page.locator('#sample button').click();await page.getByRole('heading',{name:'IQA sampling',exact:true}).waitFor();
 await page.locator('[data-page=overview]').click();await page.getByText('2 of 2 criteria verified · 100%',{exact:true}).first().waitFor();assert.equal(await page.getByText('2 of 2 criteria verified · 100%',{exact:true}).count(),2);
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go(CONFIG.email);await page.locator('[data-page=resources]').click();await page.getByText('Publish a resource',{exact:true}).click();await page.locator('#resource [name=starter]').selectOption('consultation');assert.match(await page.locator('#resource [name=body]').inputValue(),/client/);await page.locator('#resource [name=imageFile]').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l1kAAAAASUVORK5CYII=','base64')});await page.locator('#resource button').click();await page.getByRole('button',{name:'Open learning image / document'}).click();await page.locator('#modal img').waitFor();await page.locator('#close-modal').click();
 await page.locator('[data-page=portfolio]').click();await page.getByText('Sign off a complete unit',{exact:true}).click();for(const n of ['check_0','check_1','declaration'])await page.locator(`#signoff [name=${n}]`).check();await page.locator('#signoff [name=evidence]').fill('Verified practical records');await page.locator('#signoff button').click();await page.getByRole('heading',{name:/Unit sign-off/}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('iqa@example.test');await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Sample unit sign-off'}).click();for(const n of ['sampleReason','feedback'])await page.locator(`#sample [name=${n}]`).fill('Final unit check');for(const n of ['authentic','sufficient','fair','declaration'])await page.locator(`#sample [name=${n}]`).check();await page.locator('#sample [name=outcome]').selectOption('verified');await page.locator('#sample button').click();await page.locator('#modal').waitFor({state:'hidden'});
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('learner@example.test');await page.getByText('20%',{exact:true}).waitFor();await page.screenshot({path:root+'/docs/STUDENT-PROGRESS.png',fullPage:true});
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go(CONFIG.email);await page.locator('[data-page=framework]').click();await page.locator('#framework [name=unit]').selectOption('211');await page.locator('#framework [name=confirmed]').check();await page.locator('#publish-sheet').click();await page.getByText('Sheet published. Students can now select its criteria.',{exact:true}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('learner@example.test');await page.locator('[data-page=portfolio]').click();await page.getByText('Submit assessment evidence',{exact:true}).click();await page.locator('#practical [name=unit_211]').check();await page.locator('#practical [data-criteria-unit="211"] summary').click();for(let i=0;i<13;i++)await page.locator('#practical [name=criterion_211_'+i+']').check();await page.getByText('Consultation and assessment plan',{exact:true}).click();await page.locator('#practical [name=plan_clientRef]').fill('TEST-CLIENT-01');await page.locator('#practical [name=plan_aftercare]').fill('Fictional aftercare advice');for(const n of ['consultation','service','reflection'])await page.locator('#practical [name='+n+']').fill('Fictional tapered beardline observation');await page.locator('#practical [name=declaration]').check();await page.locator('#practical button.primary').click();await page.getByRole('heading',{name:/Practical submission.*211/}).waitFor();
 await page.locator('#logout').click();await page.locator('#login').waitFor({state:'visible'});await go('tutor@example.test');await page.locator('[data-page=portfolio]').click();await page.getByRole('button',{name:'Assess submission'}).click();await page.locator('#decision [data-criteria-unit="211"] summary').click();for(let i=0;i<13;i++){await page.locator('#decision [name=criterion_211_'+i+']').check();await page.locator('#decision [name=mark_211_'+i+']').selectOption([1,2,4,11,12].includes(i)?'3':'1');}await page.locator('[data-mark-summary]').getByText('Distinction',{exact:true}).waitFor();await page.screenshot({path:root+'/docs/ASSESSOR-MARKING.png',fullPage:true});await page.locator('#decision [name=outcome]').selectOption('achieved');await page.locator('#decision [name=feedback]').fill('Tapered beardline criteria observed');await page.locator('#decision [name=declaration]').check();await page.locator('#decision button').click();await page.getByRole('heading',{name:/Assessor decision.*211/}).waitFor();const marked=items.find(r=>r.kind==='assessment'&&r.payload.marking?.length);assert.equal(marked.payload.marking[0].summary[0].total,23);assert.equal(marked.payload.marking[0].summary[0].grade,'Distinction');assert.equal(items.find(r=>r.kind==='practical'&&r.payload.consultationPlan?.clientRef==='TEST-CLIENT-01').payload.consultationPlan.aftercare,'Fictional aftercare advice');
 await page.locator('#safety').click();await page.getByRole('heading',{name:'Safeguarding & support'}).waitFor();assert.equal(await page.getByRole('link',{name:'Childline support'}).getAttribute('href'),'https://www.childline.org.uk/get-support/');await page.locator('#close-modal').click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:root+'/docs/PHONE.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),true);assert.deepEqual(errors,[]);console.log('Browser passed: dates and assignments, role fields, password indicators, check-in/register/calendar, placement confirmation, multi-unit criterion submission/assessment/IQA, review, image resource, final unit sign-off, 20% progress and mobile layout. Appwrite network simulated with real domain rules; no live writes.');
}finally{await browser.close();await new Promise(r=>server.close(r));}
